# Generated by Django 4.2.3 on 2023-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
