# Generated by Django 4.2.3 on 2023-07-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
